---
version: "3.1"
services:
  nginx:
    image: nicolasvandooren/nginxmedirad:filebeat
    # ports:
    #   - "8088:8080"
    environment:
      MEDIRAD_NGINX_ENABLE_ELASTIC: "true"
      MEDIRAD_NGINX_LOGSTASH_URL: addr:port
      MEDIRAD_NGINX_ELASTIC_INSTANCE: medirad
    logging:
      driver: json-file
      options:
        max-size: "10m"
    volumes:
      - ./conf:/usr/local/openresty/nginx/conf
      - ./openssl:/opt/local/etc/openssl
